### ISSUE TITLE
[TSFix.Keyboard] functions in tsfix.ini have various issues

### ISSUE THREAD

**Issue by KiddN7-old** [Kaldaien/TSF#1]
- _BlockLeftAlt,_ seems to not work at all. Whether I set it to true or false, my left alt always works.
- _BlockLeftCtrl,_ works just as intended in every way I can see.
- _BlockWindows,_ is ignored and/or instantly overwritten. Putting _BlockWindows=false_ does nothing, the key is still ignored in game. Quitting the game and checking _tsfix.ini_ again shows _BlockWindows=true_ even if it said _BlockWindows=false_ before the game started.

I'm running TSFix 0.0.4 on a Windows 8 machine, ToS patched with the 2/5-2016 patch.

**Comment by Kaldaien** [comment]
I actually realized the problem with the Windows Key in 0.0.4 earlier today, it will be fixed.

The Alt key, however, probably doesn't block correctly in _this_ game. That feature was for Dragon's Dogma originally, that pesky game changes UI pages if you press left control or left alt. I just never bothered to remove it from this plug-in. I don't think it has any legitimate use in Tales of Symphonia?

**Comment by Kaldaien** [comment]
The Windows key issue is fixed in 0.1.0. :+1: 

If you can explain why having left alt blocked is important, I'll look into it, heheh. I was almost considering actually removing that feature rather than fixing it. Blocking the Windows key is kind of important considering if you don't run the game in borderless window mode, accidentally pressing that is a ticket to mass frustration while you spend a good 2-3 :watch: minutes re-loading

**Comment by KiddN7-old** [comment]
> I don't think it has any legitimate use in Tales of Symphonia?

I don't think so either. I mostly got annoyed with the Windows key not working, which lead me to try the Ctrl and Alt blockers since they were right there in the same ini. Figured I'd test as much of the code as I could so I could be a good little tester =)

> The Windows key issue is fixed in 0.1.0.

Great! I'll have to update so I can win+R out of ToS to save my screenshots. :+1:
